name: gentoo-openrc-musl-cloud
run-name: gentoo-openrc-musl-cloud
on:
  schedule:
    # work through your fika you poor bastard
    - cron: "12 00 * * mon"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  gentoo-openrc-musl-cloud-amd64:
    name: Make gentoo-openrc-musl-cloud-amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd cloud-openrc-musl
          docker build \
            --platform linux/amd64 -t gentoo-openrc-musl-cloud:latest .
          ./mkimg.sh gentoo-openrc-musl-cloud gentoo-openrc-musl-cloud-amd64.raw
          sha256sum -b gentoo-openrc-musl-cloud-amd64.raw |
            tee gentoo-openrc-musl-cloud-amd64.SHA256
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: gentoo-openrc-musl-cloud-amd64
          path: |
            gentoo-openrc-musl-cloud-amd64.raw
            gentoo-openrc-musl-cloud-amd64.SHA256
          retention-days: 14
  gentoo-openrc-musl-cloud-arm64:
    name: Make gentoo-openrc-musl-cloud-arm64
    runs-on: ubuntu-arm64-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd cloud-openrc-musl
          docker build \
            --platform linux/arm64 -t gentoo-openrc-musl-cloud:latest .
          ./mkimg.sh gentoo-openrc-musl-cloud gentoo-openrc-musl-cloud-arm64.raw
          sha256sum -b gentoo-openrc-musl-cloud-arm64.raw |
            tee gentoo-openrc-musl-cloud-arm64.SHA256
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: gentoo-openrc-musl-cloud-arm64
          path: |
            gentoo-openrc-musl-cloud-arm64.raw
            gentoo-openrc-musl-cloud-arm64.SHA256
          retention-days: 14
